- name: Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: access URL in Task1
      ansible.builtin.debug:
        msg: URL in Task1 ={{URL}}
    - name: Access URL in  Task2
      ansible.builtin.debug:
        msg: URL in Task2 ={{URL}}

## Declare Varibale in  playlevel then all the  tasks can access that variable
- name: Demo on file Variables
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Access URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

