- name: Setup MySQL repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove a mariadb package
  ansible.builtin.yum:
    name:  mariadb-libs
    state: absent

- name: Install MySQL
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Grab default password
  ansible.builtin.shell: grep 'temporary passwoord' /var/log/mysqld.log | awk '{print $NF}'
  register: DEFAULT_PASSWORD

- name: Check the new password is working
  ansible.builtin.shell: echo 'show databases;' | mysql -uroot -p"{NEW_PASSWORD}"
  register: check_new_password


