- name: Install NodeJS
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Download Code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COOMPONENT}"
    APP_USER: roboshop

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Download Systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd



